---
version: "3"
services:
  # run single validator fury node to provide a local fury network for development and testing of the blockscout service end to end
  fury:
    image: fanfury/fury:latest
    entrypoint: /docker/fury/fury-entrypoint.sh
    env_file: .env
    volumes:
      - ./fury:/docker/fury
    ports:
      - "${FURY_HOST_COSMOS_API_PORT}:${FURY_CONTAINER_COSMOS_API_PORT}"
      - "${FURY_HOST_COSMOS_RPC_PORT}:${FURY_CONTAINER_COSMOS_RPC_PORT}"
      - "${FURY_HOST_EVM_RPC_PORT}:${FURY_CONTAINER_EVM_RPC_PORT}"
    # expose ports for other services to be able to connect to within
    # the default docker-compose network
    expose:
      - "${FURY_CONTAINER_COSMOS_RPC_PORT}"
      - "${FURY_CONTAINER_EVM_RPC_PORT}"
  postgres:
    env_file: .env
    build: "./db"
    volumes:
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
  blockscout:
    build: "./blockscout"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "${BLOCKSCOUT_HOST_PORT}:${BLOCKSCOUT_CONTAINER_PORT}"
